AWSTemplateFormatVersion: 2010-09-09
Description: A-New-Startup - ECS - Creates an ECS Cluster with an ALB, ready for Service(s) to be added.

Parameters:

  Prefix:
    Type: String
    Default: a-new-startup-ecs
    Description: "A Prefix to use on the resource names."

  ClusterName:
    Type: String
    Default: "ecs-demo"
    Description: "A name for the ECS cluster that will be created."
  
  VpcId:
    Description: Need a VPC where the ALB will reside.
    Type: AWS::EC2::VPC::Id
    
  PublicSubnets:
    Description: Comma delimited list of PUBLIC Subnets for the ALB
    Type: String

  LoadBalancerPort:
    Type: Number
    Default: 80
 
Resources:

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName


  
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['-', [!Ref ClusterName, LoadBalancerSecurityGroup]]
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
          CidrIp: 0.0.0.0/0
  
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        # this is the default, but is specified here in case it needs to be changed
        - Key: idle_timeout.timeout_seconds
          Value: 60
        - Key: access_logs.s3.enabled
          Value: true
        - Key: access_logs.s3.bucket
          Value: !ImportValue "a-new-startup-ecs-LoggingBucket"
        - Key: access_logs.s3.prefix
          Value: !Ref Prefix
      Name: !Join ['-', [!Ref ClusterName, LoadBalancer]]
      # "internal" is also an option
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: !Split [',', !Ref PublicSubnets]
 
Outputs:

  VpcId:
    Value: !Ref VpcId
    Export:
      Name: !Join ['-', [!Ref Prefix, 'VpcId']]
  
  PublicSubnets :
    Value: !Ref PublicSubnets
    Export:
      Name: !Join ['-', [!Ref Prefix, 'PublicSubnets']]

  Cluster:
    Value: !Ref Cluster
    Export:
      Name: !Join ['-', [!Ref Prefix, 'Cluster']]
  
  LoadBalancerSecurityGroup:
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: !Join ['-', [!Ref Prefix, 'LoadBalancerSecurityGroup']]
      
  LoadBalancerPort:
    Value: !Ref LoadBalancerPort
    Export:
      Name: !Join ['-', [!Ref Prefix, 'LoadBalancerPort']]
      
  LoadBalancer:
    Value: !Ref LoadBalancer
    Export:
      Name: !Join ['-', [!Ref Prefix, 'LoadBalancer']]

  LoadBalancerDNSName:
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Join ['-', [!Ref Prefix, 'LoadBalancerDNSName']]
    